### ISSUE TITLE
unZip the files into the Section 5

### ISSUE THREAD

**Issue by smartrtos** [PacktPublishing/Learning-Web-Scraping-with-JavaScript#4]
Hi,
Is it possible to unzip the files into the folder Section 5 instead of the Section5Zip?
Thanks :)

**Comment by Abin-Packt** [comment]
@smartrtos just clarifying, do you want to unzip the zip into Section 5. Is that correct?

**Comment by Abin-Packt** [comment]
When you unzip the file named section 5, it will get unzipped into a folder named Section 5

**Comment by smartrtos** [comment]
Yes, that is correct, I would like to unzip the project from the Section5Zip to the folder Section5. To avoid any confusion among the users, since there are already folders for each section :)

**Comment by MurtazaTinwala** [comment]
Hi @smartrtos ,

I have updated the code files now. 
Please have a look and let us know in case of any issues.
Closing the post now.

Regards,
